use accesskit::Vec2;

/// Kittest Event.
pub enum Event {
    /// An ActionRequest event. When using an application these would be generated by the
    /// screen reader.
    ActionRequest(accesskit::ActionRequest),
    /// A Simulated event, e.g. clicks or typing.
    Simulated(SimulatedEvent),
}

/// A Simulated Event. These should map to the event type of the gui framework.
///
// TODO: This is very barebones right now. We should probably make these similar to winit's event types.
pub enum SimulatedEvent {
    /// A click event. Should generate a pointer button press and release event at the given position.
    Click { position: Vec2 },
    /// A type event. Should generate a text event with the given text.
    Type { text: String },
}
