name: Cargo Machete

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize ]

jobs:
  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95

      - name: Machete Check
        ## The official cargo-machete action; installs and runs it
        uses: bnjbvr/cargo-machete@v0.9.2
