# Copied from https://github.com/rerun-io/rerun_template
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize ]

name: Link checker

jobs:
  link-checker:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Restore link checker cache
        uses: actions/cache@v6
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # Check https://github.com/lycheeverse/lychee on how to run locally.
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          fail: true
          lycheeVersion: "v0.24.2"
          # When given a directory, lychee checks only markdown, html and text files, everything else we have to glob in manually.
          args: |
            --base . --cache --max-cache-age 1d . "**/*.rs" "**/*.toml" "**/*.hpp" "**/*.cpp" "**/CMakeLists.txt" "**/*.py" "**/*.yml"
